#
# Authors:     PN
# Maintainers: PN
# Copyright:   2024, UWCHR, GPL v2 or later
# ============================================
# ice-detain/docs/Makefile

.PHONY: all clean

all: \
		../write/output/index.html
	cp -r ../write/output/* .

clean:
	rm output/*

# done.
